### ISSUE TITLE
Cogdebugger probe name is truncated

### ISSUE THREAD

**Issue by juliesymons** [hpe-cct/cct-core#2]
When I run the cogdebugger with one of the examples from the neuralnetwork toolkit, some of the field names do not display correctly. The names are truncated to what is after the right-most period.

For example, if I run TwoLayerNet.scala from the examples directory, in the graph there are fields: "fc1.output.weights.forward" and "fc2.output.weights.forward". If I double-click on each of these to display their values in the "Probes" panel, both have the same window title of "forward". This makes it difficult to distinguish between the two different fields.

I am using Cog X 5.0.0-alpha.3.

**Comment by tobingonzalez** [comment]
The truncated probed field names on the desktop UI was a stylistic holdover from the Cog 3.0 era.  I don't remember exactly why we decided to do things that way, but I'm not against showing the full field name on the desktop windows, and I haven't heard objections from other team members.  I've accepted your pull request for that change, so I'm closing this issue. 

As an aside: this makes me wonder if we shouldn't introduce a user settings/preferences menu to help customize the debugger UI.
